# Setup
title:               Bitácora de fernand0
tagline:             'Cambiando de aires'
description:         'Internet, cultura libre, redes sociales, ...'
url:                 http://blog.elmundoesimperfecto.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Fernando Tricas García
  url:               https://elmundoesimperfecto.com/
  email:             blog@elmundoesimperfecto.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
